-- instyle_final_migration.sql

-- Placeholder for salon_id. Please replace 'YOUR_SALON_ID_HERE' with the actual salon ID for Instyle Hair Boutique.
-- You might need to fetch this from your 'salons' table or environment variables.
SET @instyle_salon_id = 'YOUR_SALON_ID_HERE';

--
-- Data for table 'services'
--
-- Please replace the placeholder data below with actual services from Instyle's SuperSaaS page.
-- Ensure 'salon_id' is set to @instyle_salon_id.
-- Example SuperSaaS services mentioned in the prompt: 'Middle & Side Installation', 'Maphondo & Lines Installation'

INSERT INTO services (id, name, description, duration_minutes, price, salon_id, created_at, updated_at)
VALUES
    ('service_id_1', 'Middle & Side Installation', 'Professional middle and side hair installation.', 120, 350.00, @instyle_salon_id, NOW(), NOW()),
    ('service_id_2', 'Maphondo & Lines Installation', 'Expert maphondo and lines hair installation.', 150, 400.00, @instyle_salon_id, NOW(), NOW()),
    ('service_id_3', 'Hair Treatment', 'Deep conditioning and hair repair treatment.', 60, 200.00, @instyle_salon_id, NOW(), NOW()),
    ('service_id_4', 'Braiding', 'Various braiding styles.', 180, 450.00, @instyle_salon_id, NOW(), NOW()),
    ('service_id_5', 'Hair Cut', 'Professional hair cutting and styling.', 45, 150.00, @instyle_salon_id, NOW(), NOW());

--
-- Data for table 'profiles' (clients)
--
-- Please replace the placeholder data below with actual client information.
-- Ensure 'salon_id' is set to @instyle_salon_id.
-- Note: 'id' should ideally be a UUID or generated by your database.
-- 'email' should be unique.

INSERT INTO profiles (id, full_name, email, phone, salon_id, created_at, updated_at)
VALUES
    ('client_id_1', 'Jane Doe', 'jane.doe@example.com', '+27712345678', @instyle_salon_id, NOW(), NOW()),
    ('client_id_2', 'John Smith', 'john.smith@example.com', '+27823456789', @instyle_salon_id, NOW(), NOW()),
    ('client_id_3', 'Alice Johnson', 'alice.j@example.com', '+27634567890', @instyle_salon_id, NOW(), NOW()),
    ('client_id_4', 'Bob Brown', 'bob.b@example.com', '+27765432109', @instyle_salon_id, NOW(), NOW());

--
-- Note on 'appointments' table:
-- The 'appointments' table will be populated by the SuperSaaS migration script and new bookings.
-- This SQL script is primarily for initial 'services' and 'profiles' data.