-- APPOINTMENTBOOKINGS SAAS SCHEMA v2.1
-- Multi-Tenant with Custom Domain Support

CREATE TABLE salons (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    subdomain TEXT UNIQUE,
    custom_domain TEXT UNIQUE,
    logo_url TEXT,
    primary_color TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    salon_id UUID REFERENCES salons(id) ON DELETE CASCADE NOT NULL,
    full_name TEXT,
    phone TEXT,
    role TEXT DEFAULT 'client' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE services (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    salon_id UUID REFERENCES salons(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    duration_minutes INT,
    price NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE appointments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    salon_id UUID REFERENCES salons(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    service_id UUID REFERENCES services(id) ON DELETE CASCADE,
    scheduled_time TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id UUID REFERENCES salons(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    agent_name TEXT,
    role TEXT,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE salons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to salons" ON salons FOR SELECT USING (true);
CREATE POLICY "Salon-scoped profile access" ON profiles FOR ALL USING (salon_id = (SELECT salon_id FROM profiles WHERE id = auth.uid()));
CREATE POLICY "Salon-scoped service access" ON services FOR ALL USING (salon_id = (SELECT salon_id FROM profiles WHERE id = auth.uid()));
CREATE POLICY "Salon-scoped appointment access" ON appointments FOR ALL USING (salon_id = (SELECT salon_id FROM profiles WHERE id = auth.uid()));
CREATE POLICY "Salon-scoped chat_log access" ON chat_logs FOR ALL USING (salon_id = (SELECT salon_id FROM profiles WHERE id = auth.uid()));
