import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import PerformanceObserver from "./components/PerformanceObserver";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <Providers>
          <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased bg-gray-50`}>
            <div className="flex flex-col min-h-screen">
              <PerformanceObserver />
              <Navbar />
              <main className="flex-grow">{children}</main>
              <Footer />
            </div>
          </body>
        </Providers>
      </CartProvider>
    </html>
  );
}
