mutation CreateCustomer @auth(level: USER) {
  customer_insert(data: {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com"
  })
}

query ListServices @auth(level: PUBLIC) {
  services {
    id
    name
    description
    durationMinutes
    price
  }
}

mutation UpdateAppointment($id: UUID!) @auth(level: USER) {
  appointment_update(
    id: $id,
    data: {
      status: "CONFIRMED"
    }
  )
}

query ListStaffMembers @auth(level: USER) {
  staffMembers {
    id
    firstName
    lastName
    bio
    email
    phoneNumber
  }
}